POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "second",
    "author": "kena",
    "url": "test",
    "likes": 4
}
###
DELETE http://localhost:3003/api/blogs/5f0b52e3db4de81270ccca62
###
PUT http://localhost:3003/api/blogs/5f0c893c95e9021670363977